# Generated by Django 5.2.4 on 2025-07-31 23:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['-criado_em'], 'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterModelOptions(
            name='clientedomain',
            options={'ordering': ['-id'], 'verbose_name': 'Domínio do Cliente', 'verbose_name_plural': 'Domínios dos Clientes'},
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='data_criacao',
        ),
        migrations.AddField(
            model_name='cliente',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True, verbose_name='Última Atualização'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='criado_em',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data de Criação'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='domain_url',
            field=models.CharField(default='placeholder.example.com', max_length=100, unique=True, verbose_name='URL do Domínio'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='on_trial',
            field=models.BooleanField(default=False, verbose_name='Em período de teste'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='paid_until',
            field=models.DateField(default='2099-12-31', verbose_name='Pago até'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome da Empresa'),
        ),
    ]
