# Generated by Django 5.2.4 on 2025-08-01 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usuarioempresa',
            unique_together={('user', 'empresa')},
        ),
    ]
